### ISSUE TITLE
Plot does not show up

### ISSUE THREAD

**Issue by nedahejazi** [OttoStruve/muler#125]
Everything seems setup, but when running muler:

import numpy
from muler.igrins import IGRINSSpectrumList
path_H = '/Users/n085h663/Documents/Sample_IGRINS_JWST/IGRINS_Our_2023/SDCH_20230119_0022.spec_a0v.fits'

spec_list = IGRINSSpectrumList.read(path_H)
spec_list.remove_nans().trim_edges().normalize().plot(color=None, ylo=0, yhi=5)

No plot shows up, while there is no error. Nothing happens

**Comment by gully** [comment]
Hi @nedahejazi, thanks for your interest in `muler` for IGRINS spectra.
Are you using a Jupyter Notebook?  If so, sometimes the no-plot-showing-up symptom you described can go away if you use the [matplotlib inline magic function](https://stackoverflow.com/questions/43027980/purpose-of-matplotlib-inline):

```python
%matplotlib inline
```

Execute a cell with that command towards the top of your notebook and then restart and re-run your notebook.  Does that solve your problem?

**Comment by nedahejazi** [comment]
Hi @gully,

Yes! That works. Thank you so much for your help.
