### ISSUE TITLE
User feedback: Units can be annoying

### ISSUE THREAD

**Issue by gully** [OttoStruve/muler#140]
@ericasaw points out that units can be annoying.  This conversation is coming up in #135 where handling the units causes problems.

**Comment by ericasaw** [comment]
for incoming power function: retain the unit after the flux is raised to an arbitrary power. up to the user to do whatever they need to make that work with any functions they apply to the spectra that come after using that function.

**Comment by gully** [comment]
I think this unit issue was handled correctly in the power function PR.  As for units being generally annoying, I agree I've experienced that friction, but have also benefitted from units, so I'm a bit torn: they're handy when you need them, but get in the way some time.  Tradeoffs.  I am not sure there is an actionable fix to that, so I will close this Issue, but please do re-open if you think we can do something to make units more seamless.  Maybe the most useful impact could be to include a "units" tutorial next time we go to add tutorials to our website.  I would welcome that change, so whoever is most keen to make such a demo is encouraged to flag a mental to-do note.
