### ISSUE TITLE
Object Name in Plots

### ISSUE THREAD

**Issue by joelburke02** [OttoStruve/muler#35]
When looking at the tutorials in muler, I don't know what object I'm looking at when the plot is constructed. Is it possible to have the name of the target object appear within the title of the plot?

**Comment by gully** [comment]
There exists a mechanism for adding the object name to a plot manually:

```python
ax = spec.plot()
ax.set_title('My Object Name')
```

While it's hypothetically possible to build-in these sorts of automatic customizations, there is some tradeoff in maintenance and usability.  For example, the name would have to exist and be properly formatted in the FITS header.  Sometimes the FITS header name has some formatting choice that does not suit the user, such as ancillary metadata "My_Object_NAME_refined_COORDINATES_visit1" and such.  If you put the name as a legend label, it may repopulate the same name for multiple overplotted spectra over and over again, bloating the display.  Handling all these scenarios becomes a maintenance burden.  So while this feature is a nice-to-have, it's not necessarily a need-to-have.  For now we recommend the users follow the manual option.  

If folks would adore this feature, please re-open this Issue and we can work on it together! :pray:
