### ISSUE TITLE
Ancillary files

### ISSUE THREAD

**Issue by gmace** [OttoStruve/muler#41]
Model file locations and download instructions could be made more clear in the muler documentation.

**Comment by gully** [comment]
Hi @gmace I just added a description for [how to get example data](https://muler.readthedocs.io/en/latest/install.html#getting-example-data) that appears to retire this Issue for muler.  Gollum still needs a robust description or method for how to retrieve all the data, so I opened an Issue over there.  I will close this Issue for now, but please re-open if you and your team have ideas to improve the user experience around quick-start.
