### ISSUE TITLE
Add an SNR attribute 

### ISSUE THREAD

**Issue by gully** [OttoStruve/muler#51]
We often use the signal-to-noise ratio (SNR) in our user tests and other applications.  We should add an SNR attribute, which is simply the ratio of flux to uncertainty.

This feature would be implemented as an attribute and not a method, so it should have a **noun** as its identifier and take no arguments.  SNR should be dimensionless.  If Uncertainty is zero or undefined we could either return an error, zero, or infinity, or estimate it from the data itself.

`signal_to_noise_ratio = spectrum.snr`

**Comment by zjzhang42** [comment]
Seems this feature can be simply expressed as follows, right?

`spectrum.snr = spectrum.flux.value / spectrum.uncertainty.array`

**Comment by gully** [comment]
Yes, that's correct!  The final implementation will have some handling for scenarios such as no uncertainty available, uncertainty is non-standard (not a Gaussian normal, this happens after resampling/interpolating), uncertainty has zeros, etc.

**Comment by gully** [comment]
specutils has some built-in methods for estimating SNR:
https://specutils.readthedocs.io/en/stable/analysis.html#snr
