### ISSUE TITLE
Add flexure correction?

### ISSUE THREAD

**Issue by kfkaplan** [OttoStruve/muler#54]
Is there any way to shift and resample a spectrum in pixel space instead wavelength space?   I need this for flexure correction for IGRINS data.

**Comment by gully** [comment]
Hi @kfkaplan yes, there is a way to access the pixel coordinates with `specutils`:  See cell `[18]` in this tutorial for an example that's probably not the most logical route, but could suffice as a workaround.  You might look in specutils for alternative routes to access that pixel coordinate spectral_axis representation:

https://muler.readthedocs.io/en/latest/tutorials/Combining_uncertainties_with_specutils.html

Can you post your findings if you consult the specutils documentation or Issues?

**Comment by kfkaplan** [comment]
I am working on adding flexure correction to the IGRINS PLP.  Since this correction is done on a per-exposure basis, it must be done in the IGRINS PLP and falls outside the scope of muler, since muler works with the reduced data.  Because of this, I am going to close this issue.
