### ISSUE TITLE
Roll back resample_list?

### ISSUE THREAD

**Issue by gully** [OttoStruve/muler#56]
Hi @kfkaplan, I have some questions about the use cases for the `resample_list` method just to make sure I am understanding it correctly.

I just double checked the placement of `resample_list` method and see that it is in EchelleSpectrum.  I think it might need to be relocated from EchelleSpectrum to one of two new locations.  It's really an operation on a SpectrumList, so it could/should be moved to EchelleSpectrumList.  Alternatively, it is an operation on a model, in which case it should be moved to [gollum's precomputed spectrum object](https://github.com/BrownDwarf/gollum/blob/main/src/gollum/precomputed_spectrum.py).  Which of these two (or separate?) use case do you envision?

We currently expect most EchelleSpectrum objects to be a single order spectrum, in which case resampling *that* to a list does not make as much sense, if the list is composed of spectra of distinct spectral regions.  Can you share a tutorial or example of how you would use the resample_list?

**Comment by kfkaplan** [comment]
It was originally intended to resample a single sample the single spectrum it is called onto the wavelength grid of a provided EchelleList object and called something like this:
```ResampledList = SingleSpectrum.resample_list(ListToResampleTo)```

The same functionality is provided by what is now in utilities.py which would be called like this
```ResampledList = resample_list(SingleSpectrum., ListToResampleTo)```

It could be moved from the EchelleList to Echelle class and called like so:
```ResampledList = ListToResampleTo(SingleSpectrum)```

It probably is easiest to just remove the method from Echelle and leave it as a stand alone definition in utilities.py.

**Comment by kfkaplan** [comment]
I will just remove it in my next pull request.

**Comment by kfkaplan** [comment]
Wow I totally forgot about this.  I just removed resample_list from echelle.py in my latest pull request Updates to normalize().  The definition in utilities.py should be the one everyone uses.

**Comment by kfkaplan** [comment]
This has been resolved in pull request #81 which is now merged with Main.  resample_list was moved to utilities.py as its own definition.
