### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by ericasaw** [OttoStruve/muler#77]
I was working with a few IGRINS spectra today and found a few things that would be nice to integrate:

- customizing the muler.echelle.EchelleSpectrumList function so the list can include specific orders (eg: I wanted to stitch together an IGRINS spectrum but exclude orders on each side that are generally not used for science due to noise)
- the ability to create Spectrum objects from existing wavelength and flux quantities (eg: like lightkurve's LightCurve constructor, EchelleSpectrum.wavelength = arr; EchelleSpectrum.flux = arr)
- utility that allows you to slice a SpectrumList and have it return a SpectrumList

**Comment by gully** [comment]
Thank you @ericasaw for experimenting with `muler` and providing this useful feedback! We highly value concrete feedback on the usability of the code, and so I was happy to see this Issue raised.

In the medium/long term I think there are some ways to expand the SpectrumList methods significantly, and I agree that the SpectrumList features are a bit lacking at the moment.  Thankfully the SpectrumList works ~almost like a regular Python list, and so I think---but am not certain---that there are workarounds to accomplish your first and third bullet points.  A useful way forward may be to make a tutorial that shows these workarounds, even if they are non-glamorous, they can get the job done.  

Would you be open to collaborating on a new tutorial that shows such workarounds.  I am happy to work together on it.

Thanks again!

**Comment by ericasaw** [comment]
Created a tutorial notebook that walks through solutions to the above requests. Solutions are round-about ways of getting to the answers but they work. Might raise questions to specutils about weird variable returns seen in muler that might be nice features to add in specutils. Discussed other improvements to muler--see other issues posted after this issue.
