### ISSUE TITLE
Sorting Spectrum by Wavelength

### ISSUE THREAD

**Issue by ericasaw** [OttoStruve/muler#84]
When using some of the native specutils methods the spectrum does need to be wavelength sorted (ie. when using extract region). Should build some sort of method in muler that gives the user the ability to sort the spectrum by increasing wavelength. (Although surprising the native specutils methods don't take care of this if it is required?)

**Comment by kfkaplan** [comment]
Adding my name here because I am interested in a solution as well.  I am actively looking into it and will submit a pull request if I can figure it out.  Indeed, it seems like specutils lacks this.

**Comment by ericasaw** [comment]
Submitted a pull request today with working solution. Doesn't seem to sort spec.meta['x_values'] yet which still needs to be resolved. @gully is working on it due to time cut short in our meeting today.

**Comment by gully** [comment]
Addressed in #85
