### ISSUE TITLE
Forbid in-place operations on RV shift

### ISSUE THREAD

**Issue by ericasaw** [OttoStruve/muler#88]
Had a code that worked, starting playing around with adding rv shifts to make line finding easier, didnt realize that even in the case 

> `new_spec = old_spec.rv_shift(value)`

the old_spec would also be rv shifted. Spent a few hours trying to figure out where all my lines were going. Maybe add an inplace = False argument to the rv_shift method or warn the user that the spectrum has already been rv shifted once?

**Comment by gully** [comment]
Good catch.  This in-place operation bug has popped up in another place (#86), we should forbid in-place operations everywhere in the code, since they have this unexpected behavior.
