### ISSUE TITLE
JOSS Review - Community Guidelines

### ISSUE THREAD

**Issue by wtgee** [OttoStruve/muler#90]
Hi all!

I've just started your JOSS review and it asks for some "Community guidelines". You do have the [Our mission and your help](https://github.com/OttoStruve/muler#our-mission-and-your-help) section, which is good, but you would generally want a specific CONTRIBUTING.md page as well. I would also strongly encourage you to have a Code of Conduct page.

The easiest way to do this is to go to [Insights -> Community Standards](https://github.com/OttoStruve/muler/community) for your repo and use the convenient "Propose" buttons.

**Comment by bmorris3** [comment]
Seconded!

**Comment by gully** [comment]
Closed by #91 ! Thank you 🙏
